### ISSUE TITLE
Issue with dragging to last position

### ISSUE THREAD

**Issue by Razelot** [ntbosscher/react-window-sortable#1] opened 2020-07-07 12:02 UTC
I am testing with your example for SortableFixedSizeList.  
Upon inspecting at the callback `onSortOrderChanged` , the value of `newIndex`  would not go above `n-2`

**Comment by ntbosscher** [comment] 2020-07-07 13:20
Hi @Razelot, congratulations on filing your first issue!

Thank you for noticing that case on `onSortOrderChanged`. Since it's been a while and I'm not sure if this is actually a problem, could you provide a reproduce case where this specific code is causing a bug? Like a codepen or something?

If there's a problem, I'd be happy to fix it. But just from glancing at it, I'm not confident that this is an issue.

**Comment by Razelot** [comment] 2020-07-07 14:36
Sure, I only copied the example from the repo:
[https://stackblitz.com/edit/react-m711yp](https://stackblitz.com/edit/react-m711yp)

I cannot seem move any element to the last position without dragging the last element itself.

**Comment by ntbosscher** [comment] 2020-07-08 12:16
@Razelot the issue should be fixed now. Please bump your `react-window-sortable` version to `1.4.9`.
Thanks so much for reporting this 👍

**Closed as completed by ntbosscher** 2020-07-08 12:16 UTC
